# Generated by Django 2.1.3 on 2018-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.IntegerField()),
                ('img', models.ImageField(upload_to='films/image')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='img',
        ),
    ]
